version: '3.8'

services:
  haproxy:
    image: haproxy:2.4
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "80:80"
      - "8404:8404"
    depends_on:
      - node
    networks:
      - app-network

  node:
    build: ./node-app
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network: