version: '3.8'

services:
    postgres:
        image: postgres
        environment:
            POSTGRES_DB: mydb
            POSTGRES_USER: tester
            POSTGRES_PASSWORD: 12341234
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - default

    python_server:
        build: 
            context: ./python-server
            dockerfile: Dockerfile
        networks:
            - default
        expose:
            - 5000
        environment:
            - DATABASE_HOST=postgres
            - DATABASE_NAME=mydb
            - DATABASE_USER=tester
            - DATABASE_PASSWORD=12341234

    proxy:
        image: haproxy
        volumes:
            - ./haproxy:/haproxy-override
            - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        links:
            - python_server
        networks:
            - default
        ports:
            - "80:80"
            - "70:70" # user:pass
        depends_on:
            - python_server

volumes:
  postgres_data:

networks:
    default:
        driver: bridge
